// C Wow tool registry — single source of truth.
// Each tool has a real processor. AI/media tools are marked integrationRequired
// and excluded from the public catalog until their engine is connected.

export type CategoryId =
  | "pdf"
  | "image"
  | "video"
  | "audio"
  | "ai-write"
  | "ai-image"
  | "file-data"
  | "developer-text"
  | "color-design"
  | "business";

export type ProcessingMode = "local" | "online" | "hybrid";
export type Availability = "ready" | "integrationRequired" | "unsupported";

export interface Category {
  id: CategoryId;
  name: string;
  slug: string;
  accent: string; // css var name
  description: string;
}

export interface ToolDef {
  id: string;
  slug: string;
  name: string;
  category: CategoryId;
  tags?: string[];
  description: string;
  keywords: string[];
  taskSynonyms: string[];
  inputKinds: string[];
  outputKinds: string[];
  batch: boolean;
  mode: ProcessingMode;
  availability: Availability;
  integration?: string;
  limits?: string;
  related?: string[];
  faqs?: { q: string; a: string }[];
  instructions?: string[];
  featured?: boolean;
  startHere?: boolean;
}

export const categories: Category[] = [
  {
    id: "pdf",
    name: "PDF & Documents",
    slug: "pdf",
    accent: "cat-pdf",
    description: "Merge, split, convert, and edit PDF documents.",
  },
  {
    id: "image",
    name: "Image",
    slug: "image",
    accent: "cat-image",
    description: "Resize, compress, convert, and edit images.",
  },
  {
    id: "video",
    name: "Video",
    slug: "video",
    accent: "cat-video",
    description: "Convert, trim, and compress video files.",
  },
  {
    id: "audio",
    name: "Audio",
    slug: "audio",
    accent: "cat-audio",
    description: "Convert, trim, and transcribe audio.",
  },
  {
    id: "ai-write",
    name: "AI Writing",
    slug: "ai-write",
    accent: "cat-ai",
    description: "Rewrite, summarize, and draft content with AI.",
  },
  {
    id: "ai-image",
    name: "AI Image",
    slug: "ai-image",
    accent: "cat-ai",
    description: "Background removal, upscaling, and generation.",
  },
  {
    id: "file-data",
    name: "Files & Data",
    slug: "file-data",
    accent: "cat-file",
    description: "Convert and clean CSV, JSON, and spreadsheets.",
  },
  {
    id: "developer-text",
    name: "Developer & Text",
    slug: "developer-text",
    accent: "cat-dev",
    description: "Text tools, encoders, and developer utilities.",
  },
  {
    id: "color-design",
    name: "Colors & Design",
    slug: "color-design",
    accent: "cat-color",
    description: "Color tools, QR codes, and design helpers.",
  },
  {
    id: "business",
    name: "Business & Everyday",
    slug: "business",
    accent: "cat-business",
    description: "Calculators, invoices, and everyday utilities.",
  },
];

export const categoryMap: Record<CategoryId, Category> = Object.fromEntries(
  categories.map((c) => [c.id, c]),
) as Record<CategoryId, Category>;

// ---- Local processors are ready. AI/media marked integrationRequired. ----
export const tools: ToolDef[] = [
  // ===== PDF & DOCUMENTS =====
  {
    id: "pdf-merge",
    slug: "pdf-merge",
    name: "Merge PDF",
    category: "pdf",
    description: "Combine multiple PDFs into one document with page ordering.",
    keywords: ["pdf", "merge", "combine", "join"],
    taskSynonyms: ["combine pdf files", "join pdfs", "merge documents"],
    inputKinds: ["application/pdf"],
    outputKinds: ["application/pdf"],
    batch: true,
    mode: "local",
    availability: "ready",
    limits: "Up to 50 MB total, 1000 pages.",
    related: ["pdf-split", "image-to-pdf"],
    instructions: [
      "Add PDF files in the order you want them merged.",
      "Drag to reorder pages or files.",
      "Click Merge to download the combined PDF.",
    ],
    faqs: [
      { q: "Are my PDFs uploaded anywhere?", a: "No. Merging happens entirely in your browser." },
    ],
    featured: true,
    startHere: true,
  },
  {
    id: "pdf-split",
    slug: "pdf-split",
    name: "Split PDF",
    category: "pdf",
    description: "Split a PDF by page ranges or extract individual pages.",
    keywords: ["pdf", "split", "extract", "pages"],
    taskSynonyms: ["split pdf", "extract pages", "separate pdf pages"],
    inputKinds: ["application/pdf"],
    outputKinds: ["application/pdf"],
    batch: false,
    mode: "local",
    availability: "ready",
    limits: "Up to 200 pages per file.",
    related: ["pdf-merge", "pdf-rotate"],
    instructions: [
      "Upload a PDF.",
      "Enter page ranges like 1-3, 5, 8-10.",
      "Download each split as a separate PDF.",
    ],
  },
  {
    id: "pdf-rotate",
    slug: "pdf-rotate",
    name: "Rotate PDF",
    category: "pdf",
    description: "Rotate all or selected pages of a PDF.",
    keywords: ["pdf", "rotate", "orientation"],
    taskSynonyms: ["rotate pdf", "turn pdf pages"],
    inputKinds: ["application/pdf"],
    outputKinds: ["application/pdf"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["pdf-split", "pdf-merge"],
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    name: "Image to PDF",
    category: "pdf",
    description: "Convert images (JPG, PNG, WebP) into a single PDF.",
    keywords: ["image", "pdf", "jpg", "png", "convert"],
    taskSynonyms: ["pictures into one document", "images to pdf", "convert images to pdf"],
    inputKinds: ["image/jpeg", "image/png", "image/webp"],
    outputKinds: ["application/pdf"],
    batch: true,
    mode: "local",
    availability: "ready",
    limits: "Up to 100 images.",
    related: ["pdf-merge", "image-resize"],
    featured: true,
  },
  {
    id: "pdf-to-text",
    slug: "pdf-to-text",
    name: "PDF to Text",
    category: "pdf",
    description: "Extract embedded text from a PDF to a TXT file.",
    keywords: ["pdf", "text", "extract", "txt"],
    taskSynonyms: ["extract text from pdf", "pdf to txt"],
    inputKinds: ["application/pdf"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
    faqs: [
      {
        q: "Does this OCR scanned documents?",
        a: "No — it extracts embedded text only. Scanned image-only PDFs need an OCR engine.",
      },
    ],
    related: ["pdf-split"],
  },
  {
    id: "pdf-to-images",
    slug: "pdf-to-images",
    name: "PDF to Images",
    category: "pdf",
    description: "Render PDF pages to PNG or JPG images, individually or as ZIP.",
    keywords: ["pdf", "image", "png", "jpg", "render"],
    taskSynonyms: ["pdf to png", "convert pdf to images"],
    inputKinds: ["application/pdf"],
    outputKinds: ["image/png", "image/jpeg"],
    batch: false,
    mode: "local",
    availability: "ready",
    limits: "Up to 100 pages.",
  },
  {
    id: "text-to-pdf",
    slug: "text-to-pdf",
    name: "Text to PDF",
    category: "pdf",
    description: "Create a PDF from plain text with proper wrapping and pagination.",
    keywords: ["text", "pdf", "create", "document"],
    taskSynonyms: ["text to pdf", "create pdf from text"],
    inputKinds: ["text/plain"],
    outputKinds: ["application/pdf"],
    batch: false,
    mode: "local",
    availability: "ready",
  },

  // ===== IMAGE =====
  {
    id: "image-resize",
    slug: "image-resize",
    name: "Resize Image",
    category: "image",
    description: "Resize images by dimensions, percentage, or fit within a box.",
    keywords: ["image", "resize", "scale", "dimensions"],
    taskSynonyms: ["make photo smaller", "resize image", "shrink image", "scale picture"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png", "image/jpeg", "image/webp"],
    batch: true,
    mode: "local",
    availability: "ready",
    limits: "Up to 8000px per side.",
    related: ["image-compress", "image-convert"],
    featured: true,
    startHere: true,
  },
  {
    id: "image-compress",
    slug: "image-compress",
    name: "Compress Image",
    category: "image",
    description: "Compress JPEG, PNG, and WebP with quality controls and size preview.",
    keywords: ["image", "compress", "optimize", "reduce size"],
    taskSynonyms: ["compress image", "reduce image size", "optimize image"],
    inputKinds: ["image/*"],
    outputKinds: ["image/jpeg", "image/png", "image/webp"],
    batch: true,
    mode: "local",
    availability: "ready",
    related: ["image-resize", "image-convert"],
    featured: true,
  },
  {
    id: "image-convert",
    slug: "image-convert",
    name: "Convert Image",
    category: "image",
    description: "Convert between PNG, JPEG, and WebP formats.",
    keywords: ["image", "convert", "format", "png", "jpg", "webp"],
    taskSynonyms: ["convert image", "change image format"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png", "image/jpeg", "image/webp"],
    batch: true,
    mode: "local",
    availability: "ready",
    related: ["image-resize", "image-compress"],
  },
  {
    id: "image-crop",
    slug: "image-crop",
    name: "Crop Image",
    category: "image",
    description: "Crop images with custom or preset aspect ratios.",
    keywords: ["image", "crop", "aspect"],
    taskSynonyms: ["crop image", "cut image"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png", "image/jpeg"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "image-rotate",
    slug: "image-rotate",
    name: "Rotate & Flip",
    category: "image",
    description: "Rotate or flip images.",
    keywords: ["image", "rotate", "flip"],
    taskSynonyms: ["rotate image", "flip image"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png", "image/jpeg"],
    batch: true,
    mode: "local",
    availability: "ready",
  },
  {
    id: "image-adjust",
    slug: "image-adjust",
    name: "Adjust Image",
    category: "image",
    description: "Adjust brightness, contrast, saturation, and grayscale.",
    keywords: ["image", "brightness", "contrast", "filter"],
    taskSynonyms: ["adjust image", "edit image colors"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png", "image/jpeg"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "image-rounded",
    slug: "image-rounded",
    name: "Round Corners",
    category: "image",
    description: "Add rounded corners or create a circular crop.",
    keywords: ["image", "rounded", "circle", "corners"],
    taskSynonyms: ["round corners", "circular crop", "make image round"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png"],
    batch: true,
    mode: "local",
    availability: "ready",
  },
  {
    id: "image-palette",
    slug: "image-palette",
    name: "Extract Palette",
    category: "image",
    description: "Extract a color palette from an image.",
    keywords: ["image", "palette", "colors", "extract"],
    taskSynonyms: ["extract colors from image", "image palette"],
    inputKinds: ["image/*"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["color-picker", "contrast-checker"],
  },
  {
    id: "image-metadata",
    slug: "image-metadata",
    name: "Image Metadata",
    category: "image",
    description: "Inspect image dimensions, type, and size.",
    keywords: ["image", "metadata", "info", "inspect"],
    taskSynonyms: ["image info", "check image details"],
    inputKinds: ["image/*"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },

  // ===== VIDEO (integration required) =====
  {
    id: "video-compress",
    slug: "video-compress",
    name: "Compress Video",
    category: "video",
    description: "Compress video files to reduce size.",
    keywords: ["video", "compress"],
    taskSynonyms: ["compress video", "reduce video size"],
    inputKinds: ["video/*"],
    outputKinds: ["video/mp4"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "FFmpeg WASM or online media engine",
  },
  {
    id: "video-trim",
    slug: "video-trim",
    name: "Trim Video",
    category: "video",
    description: "Trim video to a start and end point.",
    keywords: ["video", "trim", "cut"],
    taskSynonyms: ["trim video", "cut video"],
    inputKinds: ["video/*"],
    outputKinds: ["video/mp4"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "FFmpeg WASM or online media engine",
  },

  // ===== AUDIO (integration required) =====
  {
    id: "audio-transcribe",
    slug: "audio-transcribe",
    name: "Transcribe Audio",
    category: "audio",
    description: "Transcribe speech to text with timestamps.",
    keywords: ["audio", "transcribe", "speech", "text"],
    taskSynonyms: ["transcribe audio", "speech to text"],
    inputKinds: ["audio/*"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "Speech-to-text AI model",
  },

  // ===== AI WRITING (integration required) =====
  {
    id: "ai-rewrite",
    slug: "ai-rewrite",
    name: "Rewrite Text",
    category: "ai-write",
    description: "Rewrite text in a different tone or style.",
    keywords: ["ai", "rewrite", "text", "rephrase"],
    taskSynonyms: ["rewrite text", "rephrase", "make this email professional"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "AI inference provider",
  },
  {
    id: "ai-summarize",
    slug: "ai-summarize",
    name: "Summarize Text",
    category: "ai-write",
    description: "Summarize long text into a paragraph or bullets.",
    keywords: ["ai", "summarize", "summary", "tl;dr"],
    taskSynonyms: ["summarize text", "tldr", "shorten text"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "AI inference provider",
  },
  {
    id: "ai-grammar",
    slug: "ai-grammar",
    name: "Fix Grammar",
    category: "ai-write",
    description: "Fix grammar and spelling in your text.",
    keywords: ["ai", "grammar", "spelling", "correct"],
    taskSynonyms: ["fix grammar", "check spelling", "proofread"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "AI inference provider",
  },

  // ===== AI IMAGE (integration required) =====
  {
    id: "ai-bg-remove",
    slug: "ai-bg-remove",
    name: "Remove Background",
    category: "ai-image",
    description: "Remove image background to transparent PNG.",
    keywords: ["ai", "background", "remove", "transparent"],
    taskSynonyms: ["remove photo background", "transparent background"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png"],
    batch: true,
    mode: "online",
    availability: "integrationRequired",
    integration: "Background removal AI model",
  },
  {
    id: "ai-upscale",
    slug: "ai-upscale",
    name: "Upscale Image",
    category: "ai-image",
    description: "Increase image resolution with AI.",
    keywords: ["ai", "upscale", "enhance", "resolution"],
    taskSynonyms: ["upscale image", "enhance resolution"],
    inputKinds: ["image/*"],
    outputKinds: ["image/png"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "Image upscaling AI model",
  },
  {
    id: "ai-generate",
    slug: "ai-generate",
    name: "Generate Image",
    category: "ai-image",
    description: "Generate an image from a text prompt.",
    keywords: ["ai", "generate", "create", "image"],
    taskSynonyms: ["generate image", "ai image", "text to image"],
    inputKinds: ["text/plain"],
    outputKinds: ["image/png"],
    batch: false,
    mode: "online",
    availability: "integrationRequired",
    integration: "Image generation AI model",
  },

  // ===== FILES & DATA =====
  {
    id: "csv-to-xlsx",
    slug: "csv-to-xlsx",
    name: "CSV to Excel",
    category: "file-data",
    description: "Convert CSV files to Excel (XLSX) spreadsheets.",
    keywords: ["csv", "xlsx", "excel", "convert", "spreadsheet"],
    taskSynonyms: ["convert csv to excel", "csv to xlsx"],
    inputKinds: ["text/csv"],
    outputKinds: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    batch: true,
    mode: "local",
    availability: "ready",
    related: ["xlsx-to-csv", "csv-to-json"],
    featured: true,
    startHere: true,
  },
  {
    id: "xlsx-to-csv",
    slug: "xlsx-to-csv",
    name: "Excel to CSV",
    category: "file-data",
    description: "Convert Excel (XLSX) to CSV with a sheet selector.",
    keywords: ["xlsx", "csv", "excel", "convert"],
    taskSynonyms: ["convert excel to csv", "xlsx to csv"],
    inputKinds: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    outputKinds: ["text/csv"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["csv-to-xlsx", "xlsx-to-json"],
  },
  {
    id: "csv-to-json",
    slug: "csv-to-json",
    name: "CSV to JSON",
    category: "file-data",
    description: "Convert CSV data to JSON format.",
    keywords: ["csv", "json", "convert"],
    taskSynonyms: ["csv to json", "convert csv to json"],
    inputKinds: ["text/csv"],
    outputKinds: ["application/json"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["json-to-csv", "csv-to-xlsx"],
  },
  {
    id: "json-to-csv",
    slug: "json-to-csv",
    name: "JSON to CSV",
    category: "file-data",
    description: "Convert JSON data to CSV with a field selector.",
    keywords: ["json", "csv", "convert"],
    taskSynonyms: ["json to csv", "convert json to csv"],
    inputKinds: ["application/json"],
    outputKinds: ["text/csv"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["csv-to-json", "json-to-xlsx"],
  },
  {
    id: "json-to-xlsx",
    slug: "json-to-xlsx",
    name: "JSON to Excel",
    category: "file-data",
    description: "Convert JSON data to an Excel spreadsheet.",
    keywords: ["json", "xlsx", "excel", "convert"],
    taskSynonyms: ["json to excel", "json to xlsx"],
    inputKinds: ["application/json"],
    outputKinds: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["csv-to-xlsx", "json-to-csv"],
  },
  {
    id: "xlsx-to-json",
    slug: "xlsx-to-json",
    name: "Excel to JSON",
    category: "file-data",
    description: "Convert Excel sheet data to JSON.",
    keywords: ["xlsx", "json", "excel", "convert"],
    taskSynonyms: ["excel to json", "xlsx to json"],
    inputKinds: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    outputKinds: ["application/json"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["xlsx-to-csv", "csv-to-json"],
  },
  {
    id: "xml-json",
    slug: "xml-json",
    name: "XML ↔ JSON",
    category: "file-data",
    description: "Convert between XML and JSON formats.",
    keywords: ["xml", "json", "convert"],
    taskSynonyms: ["xml to json", "json to xml"],
    inputKinds: ["text/xml", "application/json"],
    outputKinds: ["application/json", "text/xml"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "yaml-json",
    slug: "yaml-json",
    name: "YAML ↔ JSON",
    category: "file-data",
    description: "Convert between YAML and JSON formats.",
    keywords: ["yaml", "json", "convert"],
    taskSynonyms: ["yaml to json", "json to yaml"],
    inputKinds: ["text/yaml", "application/json"],
    outputKinds: ["application/json", "text/yaml"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "csv-clean",
    slug: "csv-clean",
    name: "Clean CSV",
    category: "file-data",
    description: "Remove duplicates, trim fields, and reorder columns.",
    keywords: ["csv", "clean", "dedupe", "trim"],
    taskSynonyms: ["clean spreadsheet", "remove duplicates", "clean csv"],
    inputKinds: ["text/csv"],
    outputKinds: ["text/csv"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["csv-to-xlsx"],
    featured: true,
  },
  {
    id: "csv-split",
    slug: "csv-split",
    name: "Split CSV",
    category: "file-data",
    description: "Split a large CSV into smaller files by row count.",
    keywords: ["csv", "split", "rows"],
    taskSynonyms: ["split csv", "divide csv"],
    inputKinds: ["text/csv"],
    outputKinds: ["text/csv"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "csv-merge",
    slug: "csv-merge",
    name: "Merge CSV",
    category: "file-data",
    description: "Merge multiple CSV files into one.",
    keywords: ["csv", "merge", "combine"],
    taskSynonyms: ["merge csv files", "combine csv"],
    inputKinds: ["text/csv"],
    outputKinds: ["text/csv"],
    batch: true,
    mode: "local",
    availability: "ready",
  },
  {
    id: "zip-create",
    slug: "zip-create",
    name: "Create ZIP",
    category: "file-data",
    description: "Bundle multiple files into a ZIP archive.",
    keywords: ["zip", "archive", "compress"],
    taskSynonyms: ["create zip", "zip files", "archive files"],
    inputKinds: ["*/*"],
    outputKinds: ["application/zip"],
    batch: true,
    mode: "local",
    availability: "ready",
  },
  {
    id: "zip-extract",
    slug: "zip-extract",
    name: "Extract ZIP",
    category: "file-data",
    description: "Extract files from a ZIP archive.",
    keywords: ["zip", "extract", "unzip"],
    taskSynonyms: ["extract zip", "unzip files"],
    inputKinds: ["application/zip"],
    outputKinds: ["*/*"],
    batch: false,
    mode: "local",
    availability: "ready",
    limits: "Up to 500 files, 1GB expanded.",
  },
  {
    id: "md-html",
    slug: "md-html",
    name: "Markdown ↔ HTML",
    category: "file-data",
    description: "Convert Markdown to sanitized HTML and back.",
    keywords: ["markdown", "html", "convert"],
    taskSynonyms: ["markdown to html", "html to markdown"],
    inputKinds: ["text/markdown", "text/html"],
    outputKinds: ["text/html", "text/markdown"],
    batch: false,
    mode: "local",
    availability: "ready",
  },

  // ===== DEVELOPER & TEXT =====
  {
    id: "word-count",
    slug: "word-count",
    name: "Word Counter",
    category: "developer-text",
    description: "Count words, characters, sentences, and lines; estimate reading time.",
    keywords: ["word", "count", "character", "text"],
    taskSynonyms: ["count words", "word count", "text statistics"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "case-convert",
    slug: "case-convert",
    name: "Case Convert",
    category: "developer-text",
    description: "Convert text between upper, lower, title, camel, snake, and kebab case.",
    keywords: ["case", "convert", "uppercase", "lowercase"],
    taskSynonyms: ["convert case", "uppercase", "lowercase"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "text-clean",
    slug: "text-clean",
    name: "Clean Text",
    category: "developer-text",
    description: "Remove duplicate lines, trim whitespace, and sort lines.",
    keywords: ["text", "clean", "dedupe", "sort"],
    taskSynonyms: ["remove duplicate lines", "clean text", "sort lines"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "find-replace",
    slug: "find-replace",
    name: "Find & Replace",
    category: "developer-text",
    description: "Find and replace text with optional regex support.",
    keywords: ["find", "replace", "regex", "text"],
    taskSynonyms: ["find and replace", "replace text"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "text-diff",
    slug: "text-diff",
    name: "Text Diff",
    category: "developer-text",
    description: "Compare two texts and highlight the differences.",
    keywords: ["diff", "compare", "text"],
    taskSynonyms: ["compare text", "text diff", "find differences"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/html"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "json-format",
    slug: "json-format",
    name: "JSON Format",
    category: "developer-text",
    description: "Validate, format, and minify JSON.",
    keywords: ["json", "format", "minify", "validate", "pretty"],
    taskSynonyms: ["format json", "pretty print json", "validate json"],
    inputKinds: ["application/json"],
    outputKinds: ["application/json"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "base64",
    slug: "base64",
    name: "Base64 Encode/Decode",
    category: "developer-text",
    description: "Encode and decode Base64 with correct Unicode handling.",
    keywords: ["base64", "encode", "decode"],
    taskSynonyms: ["base64 encode", "base64 decode", "encode base64"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "url-encode",
    slug: "url-encode",
    name: "URL Encode/Decode",
    category: "developer-text",
    description: "Encode and decode URL components.",
    keywords: ["url", "encode", "decode", "percent"],
    taskSynonyms: ["url encode", "url decode", "percent encoding"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "html-entities",
    slug: "html-entities",
    name: "HTML Entities",
    category: "developer-text",
    description: "Encode and decode HTML entities.",
    keywords: ["html", "entities", "encode", "decode"],
    taskSynonyms: ["html encode", "html entities", "escape html"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "number-base",
    slug: "number-base",
    name: "Number Base Converter",
    category: "developer-text",
    description: "Convert integers between binary, octal, decimal, and hex.",
    keywords: ["number", "base", "binary", "hex", "decimal"],
    taskSynonyms: ["convert number base", "binary to decimal", "hex to decimal"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "timestamp",
    slug: "timestamp",
    name: "Unix Timestamp",
    category: "developer-text",
    description: "Convert between Unix timestamps and human-readable dates.",
    keywords: ["timestamp", "unix", "date", "time"],
    taskSynonyms: ["unix timestamp", "timestamp converter", "epoch time"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "uuid-gen",
    slug: "uuid-gen",
    name: "UUID Generator",
    category: "developer-text",
    description: "Generate UUIDs using a cryptographically secure source.",
    keywords: ["uuid", "guid", "generate", "random"],
    taskSynonyms: ["generate uuid", "uuid generator", "create guid"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "password-gen",
    slug: "password-gen",
    name: "Password Generator",
    category: "developer-text",
    description: "Generate secure random passwords. Never persisted or logged.",
    keywords: ["password", "generate", "random", "secure"],
    taskSynonyms: ["generate password", "random password", "secure password"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "hash-sha256",
    slug: "hash-sha256",
    name: "SHA-256 Hash",
    category: "developer-text",
    description: "Hash text or files with SHA-256.",
    keywords: ["sha256", "hash", "checksum"],
    taskSynonyms: ["sha256 hash", "hash text", "checksum"],
    inputKinds: ["text/plain", "*/*"],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "jwt-inspect",
    slug: "jwt-inspect",
    name: "JWT Inspector",
    category: "developer-text",
    description: "Decode a JWT payload. Does not verify authenticity.",
    keywords: ["jwt", "token", "decode", "json"],
    taskSynonyms: ["decode jwt", "inspect jwt", "jwt payload"],
    inputKinds: ["text/plain"],
    outputKinds: ["application/json"],
    batch: false,
    mode: "local",
    availability: "ready",
    faqs: [
      {
        q: "Does this verify the signature?",
        a: "No. It decodes the payload only — it does not verify authenticity.",
      },
    ],
  },
  {
    id: "regex-tester",
    slug: "regex-tester",
    name: "Regex Tester",
    category: "developer-text",
    description: "Test regular expressions against text with match highlighting.",
    keywords: ["regex", "regular expression", "test", "match"],
    taskSynonyms: ["test regex", "regex tester", "regular expression"],
    inputKinds: ["text/plain"],
    outputKinds: ["text/html"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "lorem-ipsum",
    slug: "lorem-ipsum",
    name: "Lorem Ipsum",
    category: "developer-text",
    description: "Generate placeholder text in paragraphs, sentences, or words.",
    keywords: ["lorem", "ipsum", "placeholder", "text"],
    taskSynonyms: ["lorem ipsum", "placeholder text", "dummy text"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },

  // ===== COLORS & DESIGN =====
  {
    id: "color-picker",
    slug: "color-picker",
    name: "Color Picker",
    category: "color-design",
    description: "Pick colors and convert between HEX, RGB, and HSL.",
    keywords: ["color", "picker", "hex", "rgb", "hsl"],
    taskSynonyms: ["color picker", "pick color", "hex to rgb"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["contrast-checker", "image-palette"],
  },
  {
    id: "contrast-checker",
    slug: "contrast-checker",
    name: "Contrast Checker",
    category: "color-design",
    description: "Check WCAG color contrast ratios for accessibility.",
    keywords: ["contrast", "wcag", "accessibility", "color"],
    taskSynonyms: ["contrast checker", "wcag contrast", "accessibility contrast"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
    related: ["color-picker"],
  },
  {
    id: "gradient-builder",
    slug: "gradient-builder",
    name: "Gradient Builder",
    category: "color-design",
    description: "Build CSS gradients with copyable CSS code.",
    keywords: ["gradient", "css", "color", "linear"],
    taskSynonyms: ["css gradient", "gradient generator", "make gradient"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "shadow-builder",
    slug: "shadow-builder",
    name: "Shadow Builder",
    category: "color-design",
    description: "Generate CSS box shadows with copyable CSS code.",
    keywords: ["shadow", "css", "box-shadow"],
    taskSynonyms: ["css shadow", "box shadow generator", "shadow css"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "qr-generator",
    slug: "qr-generator",
    name: "QR Code Generator",
    category: "color-design",
    description: "Generate QR codes for URLs, text, email, phone, and Wi-Fi.",
    keywords: ["qr", "code", "generate", "barcode"],
    taskSynonyms: ["qr code", "generate qr", "make qr code"],
    inputKinds: [],
    outputKinds: ["image/png", "image/svg+xml"],
    batch: false,
    mode: "local",
    availability: "ready",
    faqs: [
      {
        q: "Are my QR payloads stored?",
        a: "No. Sensitive Wi-Fi or contact contents are never persisted or logged.",
      },
    ],
  },
  {
    id: "utm-builder",
    slug: "utm-builder",
    name: "UTM Link Builder",
    category: "color-design",
    description: "Build UTM-tagged marketing URLs.",
    keywords: ["utm", "url", "marketing", "tracking"],
    taskSynonyms: ["utm builder", "utm link", "tracking url"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "aspect-ratio",
    slug: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    category: "color-design",
    description: "Calculate dimensions for a target aspect ratio.",
    keywords: ["aspect", "ratio", "dimensions", "resize"],
    taskSynonyms: ["aspect ratio calculator", "calculate dimensions"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },

  // ===== BUSINESS & EVERYDAY =====
  {
    id: "percentage-calc",
    slug: "percentage-calc",
    name: "Percentage Calculator",
    category: "business",
    description: "Calculate percentages, increases, and decreases.",
    keywords: ["percentage", "calc", "math"],
    taskSynonyms: ["percentage calculator", "calculate percentage"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "discount-calc",
    slug: "discount-calc",
    name: "Discount Calculator",
    category: "business",
    description: "Calculate sale price after a discount.",
    keywords: ["discount", "sale", "price", "calc"],
    taskSynonyms: ["discount calculator", "calculate discount", "sale price"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "margin-calc",
    slug: "margin-calc",
    name: "Margin & Markup",
    category: "business",
    description: "Calculate profit margin and markup with clear formulas.",
    keywords: ["margin", "markup", "profit", "calc"],
    taskSynonyms: ["profit margin", "markup calculator", "margin calculator"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "break-even",
    slug: "break-even",
    name: "Break-Even Calculator",
    category: "business",
    description: "Calculate the break-even point for your business.",
    keywords: ["break", "even", "calculator"],
    taskSynonyms: ["break even calculator", "break even point"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "sales-tax",
    slug: "sales-tax",
    name: "Sales Tax Calculator",
    category: "business",
    description: "Calculate sales tax on a price you enter.",
    keywords: ["sales", "tax", "calculator"],
    taskSynonyms: ["sales tax calculator", "calculate tax"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "unit-convert",
    slug: "unit-convert",
    name: "Unit Converter",
    category: "business",
    description: "Convert between length, weight, and temperature units.",
    keywords: ["unit", "convert", "length", "weight"],
    taskSynonyms: ["unit converter", "convert units", "measurement converter"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "timezone-compare",
    slug: "timezone-compare",
    name: "Time Zone Compare",
    category: "business",
    description: "Compare times across multiple time zones.",
    keywords: ["timezone", "time", "compare", "world"],
    taskSynonyms: ["time zone converter", "compare time zones", "world clock"],
    inputKinds: [],
    outputKinds: ["text/plain"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
  {
    id: "invoice-gen",
    slug: "invoice-gen",
    name: "Invoice Generator",
    category: "business",
    description: "Create an invoice or estimate PDF with line items and totals.",
    keywords: ["invoice", "estimate", "pdf", "business"],
    taskSynonyms: ["invoice generator", "create invoice", "make invoice pdf"],
    inputKinds: [],
    outputKinds: ["application/pdf"],
    batch: false,
    mode: "local",
    availability: "ready",
  },
];

// ---- Validation ----
const seenIds = new Set<string>();
const seenSlugs = new Set<string>();
for (const t of tools) {
  if (seenIds.has(t.id)) throw new Error(`Duplicate tool id: ${t.id}`);
  if (seenSlugs.has(t.slug)) throw new Error(`Duplicate tool slug: ${t.slug}`);
  seenIds.add(t.id);
  seenSlugs.add(t.slug);
}

export const readyTools = tools.filter((t) => t.availability === "ready");
export const toolMap = Object.fromEntries(tools.map((t) => [t.slug, t]));

export function toolsByCategory(cat: CategoryId): ToolDef[] {
  return readyTools.filter((t) => t.category === cat);
}

export function categoryCount(cat: CategoryId): number {
  return toolsByCategory(cat).length;
}

export function getTool(slug: string): ToolDef | undefined {
  return toolMap[slug];
}

export function searchTools(query: string): ToolDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return readyTools;
  const scored = readyTools
    .map((t) => {
      let score = 0;
      const name = t.name.toLowerCase();
      if (name === q) score += 100;
      else if (name.includes(q)) score += 50;
      if (t.keywords.some((k) => k.toLowerCase().includes(q))) score += 30;
      if (t.taskSynonyms.some((s) => s.toLowerCase().includes(q))) score += 40;
      if (t.description.toLowerCase().includes(q)) score += 10;
      if (t.tags?.some((tag) => tag.toLowerCase().includes(q))) score += 20;
      return { t, score };
    })
    .filter((x) => x.score > 0);
  scored.sort((a, b) => b.score - a.score);
  return scored.map((x) => x.t);
}
