// Maps tool slugs to their React components.
import { ImageResizeTool } from "./image-resize";
import {
  ImageCompressTool,
  ImageConvertTool,
  ImageRotateTool,
  ImageAdjustTool,
  ImageRoundedTool,
  ImagePaletteTool,
} from "./image-tools";
import {
  PdfMergeTool,
  PdfSplitTool,
  PdfRotateTool,
  ImageToPdfTool,
  TextToPdfTool,
} from "./pdf-tools";
import {
  CsvToXlsxTool,
  XlsxToCsvTool,
  CsvToJsonTool,
  JsonToCsvTool,
  JsonToXlsxTool,
  XlsxToJsonTool,
  XmlJsonTool,
  YamlJsonTool,
  CsvCleanTool,
  CsvSplitTool,
  CsvMergeTool,
  ZipCreateTool,
  ZipExtractTool,
  MdHtmlTool,
} from "./data-tools";
import {
  WordCountTool,
  CaseConvertTool,
  TextCleanTool,
  FindReplaceTool,
  TextDiffTool,
  JsonFormatTool,
  Base64Tool,
  UrlEncodeTool,
  HtmlEntitiesTool,
  NumberBaseTool,
  TimestampTool,
  UuidGenTool,
  PasswordGenTool,
  HashSha256Tool,
  JwtInspectTool,
  RegexTesterTool,
  LoremIpsumTool,
} from "./text-tools";
import {
  ColorPickerTool,
  ContrastCheckerTool,
  GradientBuilderTool,
  ShadowBuilderTool,
  QrGeneratorTool,
  UtmBuilderTool,
  AspectRatioTool,
} from "./color-tools";
import {
  PercentageCalcTool,
  DiscountCalcTool,
  MarginCalcTool,
  BreakEvenTool,
  SalesTaxTool,
  UnitConvertTool,
  TimezoneCompareTool,
  InvoiceGenTool,
} from "./business-tools";

export const toolComponents: Record<string, React.ComponentType> = {
  "image-resize": ImageResizeTool,
  "image-compress": ImageCompressTool,
  "image-convert": ImageConvertTool,
  "image-rotate": ImageRotateTool,
  "image-adjust": ImageAdjustTool,
  "image-rounded": ImageRoundedTool,
  "image-palette": ImagePaletteTool,
  "pdf-merge": PdfMergeTool,
  "pdf-split": PdfSplitTool,
  "pdf-rotate": PdfRotateTool,
  "image-to-pdf": ImageToPdfTool,
  "text-to-pdf": TextToPdfTool,
  "csv-to-xlsx": CsvToXlsxTool,
  "xlsx-to-csv": XlsxToCsvTool,
  "csv-to-json": CsvToJsonTool,
  "json-to-csv": JsonToCsvTool,
  "json-to-xlsx": JsonToXlsxTool,
  "xlsx-to-json": XlsxToJsonTool,
  "xml-json": XmlJsonTool,
  "yaml-json": YamlJsonTool,
  "csv-clean": CsvCleanTool,
  "csv-split": CsvSplitTool,
  "csv-merge": CsvMergeTool,
  "zip-create": ZipCreateTool,
  "zip-extract": ZipExtractTool,
  "md-html": MdHtmlTool,
  "word-count": WordCountTool,
  "case-convert": CaseConvertTool,
  "text-clean": TextCleanTool,
  "find-replace": FindReplaceTool,
  "text-diff": TextDiffTool,
  "json-format": JsonFormatTool,
  base64: Base64Tool,
  "url-encode": UrlEncodeTool,
  "html-entities": HtmlEntitiesTool,
  "number-base": NumberBaseTool,
  timestamp: TimestampTool,
  "uuid-gen": UuidGenTool,
  "password-gen": PasswordGenTool,
  "hash-sha256": HashSha256Tool,
  "jwt-inspect": JwtInspectTool,
  "regex-tester": RegexTesterTool,
  "lorem-ipsum": LoremIpsumTool,
  "color-picker": ColorPickerTool,
  "contrast-checker": ContrastCheckerTool,
  "gradient-builder": GradientBuilderTool,
  "shadow-builder": ShadowBuilderTool,
  "qr-generator": QrGeneratorTool,
  "utm-builder": UtmBuilderTool,
  "aspect-ratio": AspectRatioTool,
  "percentage-calc": PercentageCalcTool,
  "discount-calc": DiscountCalcTool,
  "margin-calc": MarginCalcTool,
  "break-even": BreakEvenTool,
  "sales-tax": SalesTaxTool,
  "unit-convert": UnitConvertTool,
  "timezone-compare": TimezoneCompareTool,
  "invoice-gen": InvoiceGenTool,
};
