import type { ToolDefinition } from "./tool-types";

// AI and media tools require external engines/providers. They are marked
// "integration-required" so they are kept as configuration but excluded from
// the public READY_TOOLS catalog until their engine is connected.

export const AI_TOOLS: ToolDefinition[] = [
  {
    id: "ai-rewrite",
    slug: "ai-rewrite",
    name: "Rewrite Text",
    category: "ai-write",
    description: "Rewrite text in a different tone or style.",
    keywords: ["ai", "rewrite", "text", "rephrase"],
    synonyms: ["rewrite text", "rephrase", "make this email professional"],
    inputKinds: ["text"],
    accepts: ["text/plain"],
    outputs: ["text/plain"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "AI inference provider",
    seoTitle: "Rewrite Text with AI | C Wow",
    seoDescription: "Rewrite text in a different tone or style with AI.",
  },
  {
    id: "ai-summarize",
    slug: "ai-summarize",
    name: "Summarize Text",
    category: "ai-write",
    description: "Summarize long text into a paragraph or bullets.",
    keywords: ["ai", "summarize", "summary", "tldr"],
    synonyms: ["summarize text", "tldr", "shorten text"],
    inputKinds: ["text"],
    accepts: ["text/plain"],
    outputs: ["text/plain"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "AI inference provider",
    seoTitle: "Summarize Text with AI | C Wow",
    seoDescription: "Summarize long text into a paragraph or bullets with AI.",
  },
  {
    id: "ai-grammar",
    slug: "ai-grammar",
    name: "Fix Grammar",
    category: "ai-write",
    description: "Fix grammar and spelling in your text.",
    keywords: ["ai", "grammar", "spelling", "correct"],
    synonyms: ["fix grammar", "check spelling", "proofread"],
    inputKinds: ["text"],
    accepts: ["text/plain"],
    outputs: ["text/plain"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "AI inference provider",
    seoTitle: "Fix Grammar with AI | C Wow",
    seoDescription: "Fix grammar and spelling in your text with AI.",
  },
  {
    id: "ai-bg-remove",
    slug: "ai-bg-remove",
    name: "Remove Background",
    category: "ai-image",
    description: "Remove image background to transparent PNG.",
    keywords: ["ai", "background", "remove", "transparent"],
    synonyms: ["remove photo background", "transparent background"],
    inputKinds: ["image"],
    accepts: ["image/*"],
    outputs: ["image/png"],
    batch: true,
    mode: "online",
    status: "integration-required",
    integration: "Background removal AI model",
    seoTitle: "Remove Image Background with AI | C Wow",
    seoDescription: "Remove image background to a transparent PNG with AI.",
  },
  {
    id: "ai-upscale",
    slug: "ai-upscale",
    name: "Upscale Image",
    category: "ai-image",
    description: "Increase image resolution with AI.",
    keywords: ["ai", "upscale", "enhance", "resolution"],
    synonyms: ["upscale image", "enhance resolution"],
    inputKinds: ["image"],
    accepts: ["image/*"],
    outputs: ["image/png"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "Image upscaling AI model",
    seoTitle: "Upscale Image with AI | C Wow",
    seoDescription: "Increase image resolution with AI.",
  },
  {
    id: "ai-generate",
    slug: "ai-generate",
    name: "Generate Image",
    category: "ai-image",
    description: "Generate an image from a text prompt.",
    keywords: ["ai", "generate", "create", "image"],
    synonyms: ["generate image", "ai image", "text to image"],
    inputKinds: ["text"],
    accepts: ["text/plain"],
    outputs: ["image/png"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "Image generation AI model",
    seoTitle: "Generate Image from Text with AI | C Wow",
    seoDescription: "Generate an image from a text prompt with AI.",
  },
];

export const MEDIA_TOOLS: ToolDefinition[] = [
  {
    id: "video-compress",
    slug: "video-compress",
    name: "Compress Video",
    category: "video",
    description: "Compress video files to reduce size.",
    keywords: ["video", "compress"],
    synonyms: ["compress video", "reduce video size"],
    inputKinds: ["file"],
    accepts: ["video/*"],
    outputs: ["video/mp4"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "FFmpeg WASM or online media engine",
    seoTitle: "Compress Video Free | C Wow",
    seoDescription: "Compress video files to reduce size.",
  },
  {
    id: "video-trim",
    slug: "video-trim",
    name: "Trim Video",
    category: "video",
    description: "Trim video to a start and end point.",
    keywords: ["video", "trim", "cut"],
    synonyms: ["trim video", "cut video"],
    inputKinds: ["file"],
    accepts: ["video/*"],
    outputs: ["video/mp4"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "FFmpeg WASM or online media engine",
    seoTitle: "Trim Video Free | C Wow",
    seoDescription: "Trim video to a start and end point.",
  },
  {
    id: "audio-transcribe",
    slug: "audio-transcribe",
    name: "Transcribe Audio",
    category: "audio",
    description: "Transcribe speech to text with timestamps.",
    keywords: ["audio", "transcribe", "speech", "text"],
    synonyms: ["transcribe audio", "speech to text"],
    inputKinds: ["file"],
    accepts: ["audio/*"],
    outputs: ["text/plain"],
    batch: false,
    mode: "online",
    status: "integration-required",
    integration: "Speech-to-text AI model",
    seoTitle: "Transcribe Audio to Text | C Wow",
    seoDescription: "Transcribe speech to text with timestamps.",
  },
];
