import type { ToolDefinition } from "./tool-types";

export const COLOR_DESIGN_TOOLS: ToolDefinition[] = [
  {
    id: "color-picker",
    slug: "color-picker",
    name: "Color Picker & Converter",
    category: "color-design",
    description: "Pick a color and convert between HEX, RGB, and HSL with alpha.",
    keywords: ["color", "picker", "hex", "rgb", "hsl", "convert", "alpha"],
    synonyms: ["color picker", "hex to rgb", "rgb to hex", "color converter"],
    inputKinds: ["color"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["palette-builder", "contrast-checker", "gradient-builder"],
    seoTitle: "Color Picker & HEX/RGB/HSL Converter Free | C Wow",
    seoDescription:
      "Pick a color and convert between HEX, RGB, and HSL with alpha. Free and browser-based.",
  },
  {
    id: "palette-builder",
    slug: "palette-builder",
    name: "Palette Builder",
    category: "color-design",
    description: "Build a color palette, adjust shades, and export CSS variables.",
    keywords: ["color", "palette", "builder", "swatches", "css", "theme"],
    synonyms: ["color palette", "build palette", "palette generator"],
    inputKinds: ["color"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["color-picker", "contrast-checker", "gradient-builder"],
    seoTitle: "Color Palette Builder Free Online | C Wow",
    seoDescription:
      "Build a color palette, adjust shades, and export CSS variables. Free and browser-based.",
  },
  {
    id: "contrast-checker",
    slug: "contrast-checker",
    name: "Contrast Checker",
    category: "color-design",
    description: "Check WCAG color contrast ratios between foreground and background.",
    keywords: ["contrast", "wcag", "accessibility", "color", "ratio", "aa", "aaa"],
    synonyms: ["contrast checker", "wcag contrast", "accessibility contrast"],
    inputKinds: ["color"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["color-picker", "palette-builder"],
    seoTitle: "WCAG Color Contrast Checker Free Online | C Wow",
    seoDescription:
      "Check WCAG color contrast ratios between foreground and background colors. Free and browser-based.",
  },
  {
    id: "gradient-builder",
    slug: "gradient-builder",
    name: "CSS Gradient Builder",
    category: "color-design",
    description: "Build linear and radial CSS gradients with copyable CSS.",
    keywords: ["css", "gradient", "linear", "radial", "builder", "background"],
    synonyms: ["gradient generator", "css gradient", "make gradient"],
    inputKinds: ["color"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["color-picker", "palette-builder", "shadow-builder"],
    seoTitle: "CSS Gradient Builder Free Online | C Wow",
    seoDescription:
      "Build linear and radial CSS gradients with copyable CSS. Free and browser-based.",
  },
  {
    id: "shadow-builder",
    slug: "css-shadow-builder",
    name: "CSS Shadow Generator",
    category: "color-design",
    description: "Design box shadows with live preview and copyable CSS.",
    keywords: ["css", "box", "shadow", "generator", "drop", "shadow"],
    synonyms: ["box shadow generator", "css shadow", "shadow maker"],
    inputKinds: ["color"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["gradient-builder", "color-picker"],
    seoTitle: "CSS Box Shadow Generator Free Online | C Wow",
    seoDescription:
      "Design box shadows with live preview and copyable CSS. Free and browser-based.",
  },
  {
    id: "qr-generator",
    slug: "qr-code-generator",
    name: "QR Code Generator",
    category: "color-design",
    description: "Generate QR codes for URLs, text, email, phone, or Wi-Fi as SVG or PNG.",
    keywords: ["qr", "code", "generate", "url", "wifi", "svg", "png"],
    synonyms: ["qr generator", "make qr code", "create qr"],
    inputKinds: ["form"],
    outputs: ["image/png", "image/svg+xml"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "Sensitive Wi-Fi or contact payloads are never stored or shared.",
    related: ["color-picker", "gradient-builder"],
    featured: true,
    seoTitle: "Free QR Code Generator (URL, Wi-Fi, SVG, PNG) | C Wow",
    seoDescription:
      "Generate QR codes for URLs, text, email, phone, or Wi-Fi and download as SVG or PNG. Free and browser-based.",
  },
  {
    id: "utm-builder",
    slug: "utm-link-builder",
    name: "UTM Link Builder",
    category: "color-design",
    description: "Build UTM tracking URLs with validated parameters and copyable output.",
    keywords: ["utm", "link", "url", "tracking", "marketing", "campaign"],
    synonyms: ["utm builder", "utm link", "tracking url"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["qr-generator", "url-encode"],
    seoTitle: "UTM Link Builder Free Online | C Wow",
    seoDescription:
      "Build UTM tracking URLs with validated parameters and copyable output. Free and browser-based.",
  },
  {
    id: "aspect-ratio-calc",
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    category: "color-design",
    description: "Calculate matching dimensions for any aspect ratio.",
    keywords: ["aspect", "ratio", "calculator", "dimensions", "resize", "image"],
    synonyms: ["aspect ratio calculator", "image dimensions", "ratio calc"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["image-resize", "color-picker"],
    seoTitle: "Aspect Ratio Calculator Free Online | C Wow",
    seoDescription: "Calculate matching dimensions for any aspect ratio. Free and browser-based.",
  },
];

export const BUSINESS_TOOLS: ToolDefinition[] = [
  {
    id: "percentage-calc",
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    category: "business",
    description: "Calculate percentages, percentage change, and the percentage of a number.",
    keywords: ["percentage", "calculator", "percent", "change", "increase", "decrease"],
    synonyms: ["percentage calculator", "percent of", "percent change"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["discount-calc", "margin-calc", "sales-tax-calc"],
    seoTitle: "Percentage Calculator Free Online | C Wow",
    seoDescription:
      "Calculate percentages, percentage change, and the percentage of a number. Free and browser-based.",
  },
  {
    id: "discount-calc",
    slug: "discount-calculator",
    name: "Discount Calculator",
    category: "business",
    description: "Calculate the final price after a discount and your savings.",
    keywords: ["discount", "calculator", "price", "sale", "savings", "off"],
    synonyms: ["discount calculator", "sale price", "percent off"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["percentage-calc", "margin-calc", "sales-tax-calc"],
    seoTitle: "Discount Calculator Free Online | C Wow",
    seoDescription:
      "Calculate the final price after a discount and your savings. Free and browser-based.",
  },
  {
    id: "margin-calc",
    slug: "profit-margin-calculator",
    name: "Profit Margin & Markup",
    category: "business",
    description: "Calculate profit margin and markup with clearly different formulas.",
    keywords: ["profit", "margin", "markup", "calculator", "business", "pricing"],
    synonyms: ["profit margin calculator", "markup calculator", "margin calc"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["discount-calc", "percentage-calc", "break-even-calc"],
    seoTitle: "Profit Margin & Markup Calculator Free | C Wow",
    seoDescription:
      "Calculate profit margin and markup with clearly different formulas. Free and browser-based.",
  },
  {
    id: "break-even-calc",
    slug: "break-even-calculator",
    name: "Break-Even Calculator",
    category: "business",
    description: "Find the sales volume where revenue equals costs.",
    keywords: ["break", "even", "calculator", "business", "revenue", "costs"],
    synonyms: ["break even calculator", "break even point", "bea"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["margin-calc", "percentage-calc"],
    seoTitle: "Break-Even Calculator Free Online | C Wow",
    seoDescription: "Find the sales volume where revenue equals costs. Free and browser-based.",
  },
  {
    id: "sales-tax-calc",
    slug: "sales-tax-calculator",
    name: "Sales Tax Calculator",
    category: "business",
    description: "Add a user-entered sales tax rate to a price.",
    keywords: ["sales", "tax", "calculator", "price", "vat", "rate"],
    synonyms: ["sales tax calculator", "tax calculator", "add tax"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "You enter the tax rate. This does not look up local rates.",
    related: ["discount-calc", "percentage-calc", "margin-calc"],
    seoTitle: "Sales Tax Calculator Free Online | C Wow",
    seoDescription: "Add a user-entered sales tax rate to a price. Free and browser-based.",
  },
  {
    id: "unit-converter",
    slug: "unit-converter",
    name: "Unit Converter",
    category: "business",
    description: "Convert between length, weight, temperature, and volume units.",
    keywords: [
      "unit",
      "converter",
      "length",
      "weight",
      "temperature",
      "volume",
      "metric",
      "imperial",
    ],
    synonyms: ["unit converter", "convert units", "metric converter"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["percentage-calc", "aspect-ratio-calc"],
    seoTitle: "Unit Converter Free Online (Length, Weight, Temp) | C Wow",
    seoDescription:
      "Convert between length, weight, temperature, and volume units. Free and browser-based.",
  },
  {
    id: "timezone-compare",
    slug: "time-zone-comparison",
    name: "Time Zone Comparison",
    category: "business",
    description: "Compare the current time across multiple time zones side by side.",
    keywords: ["time", "zone", "comparison", "world", "clock", "timezone"],
    synonyms: ["time zone converter", "world clock", "compare time zones"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["timestamp-converter", "unit-converter"],
    seoTitle: "Time Zone Comparison Free Online | C Wow",
    seoDescription:
      "Compare the current time across multiple time zones side by side. Free and browser-based.",
  },
  {
    id: "invoice-generator",
    slug: "invoice-generator",
    name: "Invoice & Estimate Generator",
    category: "business",
    description: "Create an invoice or estimate with line items and download a PDF.",
    keywords: ["invoice", "estimate", "generator", "pdf", "business", "billing"],
    synonyms: ["invoice generator", "make invoice", "create estimate", "billing pdf"],
    inputKinds: ["form"],
    outputs: ["application/pdf"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "Entered data stays on your device. Nothing is sent anywhere.",
    related: ["text-to-pdf", "percentage-calc"],
    featured: true,
    seoTitle: "Free Invoice & Estimate Generator (PDF) | C Wow",
    seoDescription:
      "Create an invoice or estimate with line items and download a PDF. Data stays on your device. Free and browser-based.",
  },
];
