import type { ToolDefinition } from "./tool-types";

export const DATA_TOOLS: ToolDefinition[] = [
  {
    id: "csv-to-xlsx",
    slug: "csv-to-excel",
    name: "CSV to Excel",
    category: "file-data",
    description: "Convert a CSV file into a formatted XLSX spreadsheet.",
    keywords: ["csv", "xlsx", "excel", "convert", "spreadsheet"],
    synonyms: ["csv to excel", "convert csv to xlsx", "csv to spreadsheet"],
    inputKinds: ["file"],
    accepts: ["text/csv", "application/vnd.ms-excel"],
    outputs: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["xlsx-to-csv", "csv-to-json", "json-to-csv"],
    featured: true,
    seoTitle: "Convert CSV to Excel (XLSX) Free Online | C Wow",
    seoDescription:
      "Convert a CSV file into a formatted XLSX spreadsheet. Handles quoted fields, Unicode, and leading zeroes. Free and browser-based.",
  },
  {
    id: "xlsx-to-csv",
    slug: "xlsx-to-csv",
    name: "Excel to CSV",
    category: "file-data",
    description: "Convert an XLSX spreadsheet to CSV with a sheet selector.",
    keywords: ["xlsx", "csv", "excel", "convert", "spreadsheet"],
    synonyms: ["excel to csv", "xlsx to csv", "spreadsheet to csv"],
    inputKinds: ["file"],
    accepts: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    outputs: ["text/csv"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["csv-to-xlsx", "xlsx-to-json", "csv-to-json"],
    seoTitle: "Convert Excel (XLSX) to CSV Free Online | C Wow",
    seoDescription:
      "Convert an XLSX spreadsheet to CSV with a sheet selector. Free and browser-based.",
  },
  {
    id: "csv-to-json",
    slug: "csv-to-json",
    name: "CSV to JSON",
    category: "file-data",
    description: "Convert CSV data into a JSON array of objects.",
    keywords: ["csv", "json", "convert", "data"],
    synonyms: ["csv to json", "convert csv to json"],
    inputKinds: ["file"],
    accepts: ["text/csv"],
    outputs: ["application/json"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["json-to-csv", "csv-to-xlsx", "json-to-xlsx"],
    seoTitle: "Convert CSV to JSON Free Online | C Wow",
    seoDescription:
      "Convert CSV data into a JSON array of objects. Handles quoted fields and Unicode. Free and browser-based.",
  },
  {
    id: "json-to-csv",
    slug: "json-to-csv",
    name: "JSON to CSV",
    category: "file-data",
    description: "Flatten a JSON array of objects into CSV with a field selector.",
    keywords: ["json", "csv", "convert", "flatten", "data"],
    synonyms: ["json to csv", "convert json to csv"],
    inputKinds: ["file"],
    accepts: ["application/json"],
    outputs: ["text/csv"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["csv-to-json", "json-to-xlsx", "json-to-yaml"],
    seoTitle: "Convert JSON to CSV Free Online | C Wow",
    seoDescription:
      "Flatten a JSON array of objects into CSV with a field selector. Free and browser-based.",
  },
  {
    id: "json-to-xlsx",
    slug: "json-to-excel",
    name: "JSON to Excel",
    category: "file-data",
    description: "Convert a JSON array of objects into an XLSX spreadsheet.",
    keywords: ["json", "xlsx", "excel", "convert", "spreadsheet"],
    synonyms: ["json to excel", "json to xlsx"],
    inputKinds: ["file"],
    accepts: ["application/json"],
    outputs: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["csv-to-xlsx", "json-to-csv", "csv-to-json"],
    seoTitle: "Convert JSON to Excel (XLSX) Free Online | C Wow",
    seoDescription:
      "Convert a JSON array of objects into an XLSX spreadsheet. Free and browser-based.",
  },
  {
    id: "xlsx-to-json",
    slug: "xlsx-to-json",
    name: "Excel to JSON",
    category: "file-data",
    description: "Convert XLSX sheet data into a JSON array of objects.",
    keywords: ["xlsx", "json", "excel", "convert", "spreadsheet"],
    synonyms: ["excel to json", "xlsx to json"],
    inputKinds: ["file"],
    accepts: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    outputs: ["application/json"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["xlsx-to-csv", "csv-to-json", "json-to-xlsx"],
    seoTitle: "Convert Excel (XLSX) to JSON Free Online | C Wow",
    seoDescription: "Convert XLSX sheet data into a JSON array of objects. Free and browser-based.",
  },
  {
    id: "json-to-yaml",
    slug: "json-to-yaml",
    name: "JSON to YAML",
    category: "file-data",
    description: "Convert JSON into clean, readable YAML.",
    keywords: ["json", "yaml", "convert", "config"],
    synonyms: ["json to yaml", "convert json to yaml"],
    inputKinds: ["text"],
    accepts: ["application/json"],
    outputs: ["text/yaml"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["yaml-to-json", "json-to-csv", "json-formatter"],
    seoTitle: "Convert JSON to YAML Free Online | C Wow",
    seoDescription: "Convert JSON into clean, readable YAML. Free and browser-based.",
  },
  {
    id: "yaml-to-json",
    slug: "yaml-to-json",
    name: "YAML to JSON",
    category: "file-data",
    description: "Convert YAML into formatted JSON.",
    keywords: ["yaml", "json", "convert", "config"],
    synonyms: ["yaml to json", "convert yaml to json"],
    inputKinds: ["text"],
    outputs: ["application/json"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["json-to-yaml", "json-formatter"],
    seoTitle: "Convert YAML to JSON Free Online | C Wow",
    seoDescription: "Convert YAML into formatted JSON. Free and browser-based.",
  },
  {
    id: "csv-clean",
    slug: "clean-csv",
    name: "Clean CSV Data",
    category: "file-data",
    description: "Trim whitespace, remove duplicate rows, and reorder columns.",
    keywords: ["csv", "clean", "trim", "deduplicate", "remove", "duplicates", "columns"],
    synonyms: ["clean spreadsheet", "remove duplicates csv", "trim csv"],
    inputKinds: ["file"],
    accepts: ["text/csv"],
    outputs: ["text/csv"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["csv-to-xlsx", "csv-to-json", "csv-split"],
    featured: true,
    seoTitle: "Clean CSV Data Free — Trim, Dedupe, Reorder | C Wow",
    seoDescription:
      "Trim whitespace, remove duplicate rows, and reorder columns in a CSV. Free and browser-based.",
  },
  {
    id: "csv-split",
    slug: "split-csv",
    name: "Split CSV by Rows",
    category: "file-data",
    description: "Split a large CSV into multiple files by row count.",
    keywords: ["csv", "split", "rows", "divide", "chunk"],
    synonyms: ["split csv", "divide csv", "csv chunks"],
    inputKinds: ["file"],
    accepts: ["text/csv"],
    outputs: ["text/csv"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["csv-merge", "clean-csv", "csv-to-xlsx"],
    seoTitle: "Split CSV by Row Count Free Online | C Wow",
    seoDescription: "Split a large CSV into multiple files by row count. Free and browser-based.",
  },
  {
    id: "csv-merge",
    slug: "merge-csv",
    name: "Merge CSV Files",
    category: "file-data",
    description: "Combine multiple CSV files with matching columns into one.",
    keywords: ["csv", "merge", "combine", "join", "concatenate"],
    synonyms: ["merge csv files", "combine csv", "join csv"],
    inputKinds: ["file"],
    accepts: ["text/csv"],
    outputs: ["text/csv"],
    batch: true,
    mode: "local",
    status: "ready",
    related: ["csv-split", "clean-csv", "csv-to-xlsx"],
    seoTitle: "Merge CSV Files Free Online | C Wow",
    seoDescription:
      "Combine multiple CSV files with matching columns into one. Free and browser-based.",
  },
  {
    id: "zip-create",
    slug: "create-zip",
    name: "Create ZIP Archive",
    category: "file-data",
    description: "Bundle multiple files into a single ZIP archive.",
    keywords: ["zip", "archive", "compress", "bundle", "files"],
    synonyms: ["create zip", "zip files", "make archive", "bundle files"],
    inputKinds: ["file"],
    outputs: ["application/zip"],
    batch: true,
    mode: "local",
    status: "ready",
    related: ["zip-extract", "image-to-pdf"],
    seoTitle: "Create ZIP Archive Free Online | C Wow",
    seoDescription: "Bundle multiple files into a single ZIP archive. Free and browser-based.",
  },
  {
    id: "zip-extract",
    slug: "extract-zip",
    name: "Extract ZIP Archive",
    category: "file-data",
    description: "Unzip a ZIP archive and download individual files.",
    keywords: ["zip", "extract", "unzip", "decompress", "archive"],
    synonyms: ["unzip", "extract zip", "open zip"],
    inputKinds: ["file"],
    accepts: ["application/zip", "application/x-zip-compressed"],
    outputs: ["application/octet-stream"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "Up to 1 GB expanded. Path traversal and unsafe entries are blocked.",
    related: ["zip-create"],
    seoTitle: "Extract ZIP Archive Free Online | C Wow",
    seoDescription:
      "Unzip a ZIP archive and download individual files safely. Free and browser-based.",
  },
  {
    id: "markdown-to-html",
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    category: "file-data",
    description: "Convert Markdown into clean, sanitized HTML.",
    keywords: ["markdown", "html", "convert", "md"],
    synonyms: ["markdown to html", "convert md to html"],
    inputKinds: ["text"],
    outputs: ["text/html"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["html-to-markdown", "json-formatter"],
    seoTitle: "Convert Markdown to HTML Free Online | C Wow",
    seoDescription: "Convert Markdown into clean, sanitized HTML. Free and browser-based.",
  },
  {
    id: "html-to-markdown",
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    category: "file-data",
    description: "Convert sanitized HTML into clean Markdown.",
    keywords: ["html", "markdown", "convert", "md"],
    synonyms: ["html to markdown", "convert html to md"],
    inputKinds: ["text"],
    outputs: ["text/markdown"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["markdown-to-html", "json-formatter"],
    seoTitle: "Convert HTML to Markdown Free Online | C Wow",
    seoDescription: "Convert sanitized HTML into clean Markdown. Free and browser-based.",
  },
];
