import type { ToolDefinition } from "./tool-types";

export const DEV_TEXT_TOOLS: ToolDefinition[] = [
  {
    id: "text-count",
    slug: "word-counter",
    name: "Word & Character Counter",
    category: "developer-text",
    description: "Count words, characters, sentences, lines, and estimate reading time.",
    keywords: ["word", "character", "count", "sentences", "lines", "reading", "time"],
    synonyms: ["word count", "character count", "count words"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["text-case", "text-diff", "remove-duplicate-lines"],
    seoTitle: "Word & Character Counter Free Online | C Wow",
    seoDescription:
      "Count words, characters, sentences, lines, and estimate reading time. Free and browser-based.",
  },
  {
    id: "text-case",
    slug: "change-text-case",
    name: "Change Text Case",
    category: "developer-text",
    description: "Convert text to upper, lower, title, sentence, or camel case.",
    keywords: ["text", "case", "upper", "lower", "title", "camel", "convert"],
    synonyms: ["change case", "uppercase", "lowercase", "title case"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["text-count", "whitespace-cleanup", "remove-duplicate-lines"],
    seoTitle: "Change Text Case Free Online | C Wow",
    seoDescription:
      "Convert text to upper, lower, title, sentence, or camel case. Free and browser-based.",
  },
  {
    id: "whitespace-cleanup",
    slug: "whitespace-cleanup",
    name: "Whitespace Cleanup",
    category: "developer-text",
    description: "Trim, collapse spaces, and normalize line endings in text.",
    keywords: ["text", "whitespace", "trim", "spaces", "cleanup", "normalize"],
    synonyms: ["remove extra spaces", "trim whitespace", "cleanup text"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["text-case", "remove-duplicate-lines", "sort-lines"],
    seoTitle: "Whitespace Cleanup Free Online | C Wow",
    seoDescription:
      "Trim, collapse spaces, and normalize line endings in text. Free and browser-based.",
  },
  {
    id: "remove-duplicate-lines",
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    category: "developer-text",
    description: "Remove duplicate lines from a list, keeping first or unique only.",
    keywords: ["text", "duplicate", "lines", "remove", "unique", "dedupe"],
    synonyms: ["remove duplicate lines", "dedupe lines", "unique lines"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["sort-lines", "whitespace-cleanup", "text-count"],
    seoTitle: "Remove Duplicate Lines Free Online | C Wow",
    seoDescription: "Remove duplicate lines from a list of text. Free and browser-based.",
  },
  {
    id: "sort-lines",
    slug: "sort-lines",
    name: "Sort Lines",
    category: "developer-text",
    description: "Sort lines alphabetically, numerically, or in reverse.",
    keywords: ["text", "sort", "lines", "alphabetical", "numeric", "reverse"],
    synonyms: ["sort lines", "alphabetize lines", "order lines"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["remove-duplicate-lines", "text-case"],
    seoTitle: "Sort Lines Free Online | C Wow",
    seoDescription:
      "Sort lines alphabetically, numerically, or in reverse. Free and browser-based.",
  },
  {
    id: "find-replace",
    slug: "find-and-replace",
    name: "Find & Replace",
    category: "developer-text",
    description: "Find and replace text with optional case sensitivity and regex.",
    keywords: ["text", "find", "replace", "search", "regex", "substitute"],
    synonyms: ["find and replace", "replace text", "search replace"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["text-case", "text-diff"],
    seoTitle: "Find & Replace Text Free Online | C Wow",
    seoDescription:
      "Find and replace text with optional case sensitivity and regex. Free and browser-based.",
  },
  {
    id: "text-diff",
    slug: "text-diff",
    name: "Text Diff",
    category: "developer-text",
    description: "Compare two blocks of text and highlight the differences.",
    keywords: ["text", "diff", "compare", "difference", "changes"],
    synonyms: ["compare text", "text difference", "diff text"],
    inputKinds: ["text"],
    outputs: ["text/html"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["find-replace", "word-counter"],
    seoTitle: "Text Diff — Compare Two Texts Free | C Wow",
    seoDescription:
      "Compare two blocks of text and highlight the differences line by line. Free and browser-based.",
  },
  {
    id: "json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    category: "developer-text",
    description: "Validate, format (pretty-print), and minify JSON.",
    keywords: ["json", "format", "validate", "pretty", "minify", "beautify"],
    synonyms: ["format json", "validate json", "beautify json", "minify json"],
    inputKinds: ["text"],
    outputs: ["application/json"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["json-to-csv", "json-to-yaml", "base64"],
    featured: true,
    seoTitle: "JSON Formatter & Validator Free Online | C Wow",
    seoDescription: "Validate, format (pretty-print), and minify JSON. Free and browser-based.",
  },
  {
    id: "base64",
    slug: "base64-encode-decode",
    name: "Base64 Encode & Decode",
    category: "developer-text",
    description: "Encode text to Base64 or decode Base64 with correct Unicode handling.",
    keywords: ["base64", "encode", "decode", "text", "binary"],
    synonyms: ["base64 encode", "base64 decode", "encode base64"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["url-encode", "json-formatter", "hash-text"],
    seoTitle: "Base64 Encode & Decode Free Online | C Wow",
    seoDescription:
      "Encode text to Base64 or decode Base64 with correct Unicode handling. Free and browser-based.",
  },
  {
    id: "url-encode",
    slug: "url-encode-decode",
    name: "URL Encode & Decode",
    category: "developer-text",
    description: "Percent-encode or decode URLs and query strings.",
    keywords: ["url", "encode", "decode", "percent", "uri", "query"],
    synonyms: ["url encode", "url decode", "percent encoding"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["base64", "html-entity"],
    seoTitle: "URL Encode & Decode Free Online | C Wow",
    seoDescription: "Percent-encode or decode URLs and query strings. Free and browser-based.",
  },
  {
    id: "html-entity",
    slug: "html-entity-encode-decode",
    name: "HTML Entity Encode & Decode",
    category: "developer-text",
    description: "Encode or decode HTML entities for safe display.",
    keywords: ["html", "entity", "encode", "decode", "escape", "entities"],
    synonyms: ["html encode", "html decode", "escape html"],
    inputKinds: ["text"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["url-encode", "base64"],
    seoTitle: "HTML Entity Encode & Decode Free Online | C Wow",
    seoDescription: "Encode or decode HTML entities for safe display. Free and browser-based.",
  },
  {
    id: "hash-text",
    slug: "sha256-hash",
    name: "SHA-256 Hash",
    category: "developer-text",
    description: "Generate a SHA-256 hash from text or a file using the Web Crypto API.",
    keywords: ["sha256", "hash", "checksum", "digest", "crypto"],
    synonyms: ["sha256 hash", "hash text", "checksum"],
    inputKinds: ["text", "file"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["uuid-generator", "password-generator", "base64"],
    seoTitle: "SHA-256 Hash Generator Free Online | C Wow",
    seoDescription:
      "Generate a SHA-256 hash from text or a file using the Web Crypto API. Free and browser-based.",
  },
  {
    id: "uuid-generator",
    slug: "uuid-generator",
    name: "UUID Generator",
    category: "developer-text",
    description: "Generate cryptographically secure UUIDs (v4) in bulk.",
    keywords: ["uuid", "guid", "generate", "random", "identifier"],
    synonyms: ["generate uuid", "uuid v4", "create guid"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["password-generator", "hash-text"],
    seoTitle: "UUID Generator (v4) Free Online | C Wow",
    seoDescription: "Generate cryptographically secure UUIDs (v4) in bulk. Free and browser-based.",
  },
  {
    id: "password-generator",
    slug: "password-generator",
    name: "Password Generator",
    category: "developer-text",
    description: "Generate strong, cryptographically secure passwords with custom rules.",
    keywords: ["password", "generate", "secure", "random", "strong"],
    synonyms: ["generate password", "password maker", "strong password"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "Generated passwords are never stored, logged, or sent anywhere.",
    related: ["uuid-generator", "hash-text"],
    seoTitle: "Strong Password Generator Free Online | C Wow",
    seoDescription:
      "Generate strong, cryptographically secure passwords with custom rules. Never stored or logged. Free and browser-based.",
  },
  {
    id: "jwt-inspector",
    slug: "jwt-inspector",
    name: "JWT Inspector",
    category: "developer-text",
    description: "Decode a JWT header and payload. Decodes only — does not verify authenticity.",
    keywords: ["jwt", "json", "web", "token", "decode", "inspect", "payload"],
    synonyms: ["decode jwt", "inspect token", "jwt decoder"],
    inputKinds: ["text"],
    outputs: ["application/json"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "This tool decodes the token. It does not verify the signature or authenticity.",
    related: ["base64", "json-formatter"],
    seoTitle: "JWT Decoder & Inspector Free Online | C Wow",
    seoDescription:
      "Decode a JWT header and payload. Decodes only — does not verify authenticity. Free and browser-based.",
  },
  {
    id: "regex-tester",
    slug: "regex-tester",
    name: "Regex Tester",
    category: "developer-text",
    description: "Test a regular expression against text and see matches highlighted.",
    keywords: ["regex", "regular", "expression", "test", "match", "pattern"],
    synonyms: ["test regex", "regex tester", "regular expression tester"],
    inputKinds: ["text"],
    outputs: ["text/html"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["find-replace", "text-diff"],
    seoTitle: "Regex Tester Free Online | C Wow",
    seoDescription:
      "Test a regular expression against text and see matches highlighted. Free and browser-based.",
  },
  {
    id: "number-base",
    slug: "number-base-converter",
    name: "Number Base Converter",
    category: "developer-text",
    description: "Convert integers between binary, octal, decimal, and hexadecimal.",
    keywords: ["number", "base", "binary", "octal", "decimal", "hex", "convert", "radix"],
    synonyms: ["binary converter", "hex converter", "base converter"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["uuid-generator", "hash-text"],
    seoTitle: "Number Base Converter (Binary, Hex, Decimal) Free | C Wow",
    seoDescription:
      "Convert integers between binary, octal, decimal, and hexadecimal. Free and browser-based.",
  },
  {
    id: "timestamp-converter",
    slug: "timestamp-converter",
    name: "Unix Timestamp Converter",
    category: "developer-text",
    description: "Convert between Unix timestamps and human-readable dates with time zones.",
    keywords: ["unix", "timestamp", "date", "time", "convert", "epoch"],
    synonyms: ["unix timestamp", "epoch converter", "date to timestamp"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["number-base", "uuid-generator"],
    seoTitle: "Unix Timestamp Converter Free Online | C Wow",
    seoDescription:
      "Convert between Unix timestamps and human-readable dates with time zones. Free and browser-based.",
  },
  {
    id: "lorem-ipsum",
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    category: "developer-text",
    description: "Generate placeholder text by paragraphs, sentences, or words.",
    keywords: ["lorem", "ipsum", "placeholder", "dummy", "text", "generate"],
    synonyms: ["lorem ipsum", "placeholder text", "dummy text"],
    inputKinds: ["form"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["word-counter", "text-case"],
    seoTitle: "Lorem Ipsum Generator Free Online | C Wow",
    seoDescription:
      "Generate placeholder text by paragraphs, sentences, or words. Free and browser-based.",
  },
];
