import type { ToolDefinition } from "./tool-types";

export const IMAGE_TOOLS: ToolDefinition[] = [
  {
    id: "image-resize",
    slug: "image-resize",
    name: "Resize Image",
    category: "image",
    tags: ["scale", "dimensions"],
    description: "Resize images by exact dimensions, percentage, or maximum edge.",
    keywords: ["image", "resize", "scale", "dimensions", "shrink", "enlarge", "smaller"],
    synonyms: ["make picture smaller", "resize photo", "scale image", "make image smaller"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["image/jpeg", "image/png", "image/webp"],
    batch: true,
    mode: "local",
    status: "ready",
    related: ["image-compress", "image-convert", "image-crop"],
    featured: true,
    seoTitle: "Resize Image Free Online (JPG, PNG, WebP) | C Wow",
    seoDescription:
      "Resize images by dimensions, percentage, or maximum edge. Batch supported, free and browser-based.",
  },
  {
    id: "image-compress",
    slug: "image-compress",
    name: "Compress Image",
    category: "image",
    description: "Reduce JPEG, PNG, or WebP file size with adjustable quality.",
    keywords: ["image", "compress", "reduce", "size", "optimize", "smaller"],
    synonyms: ["make image smaller", "compress photo", "reduce image size", "shrink image"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["image/jpeg", "image/png", "image/webp"],
    batch: true,
    mode: "local",
    status: "ready",
    related: ["image-resize", "image-convert"],
    featured: true,
    seoTitle: "Compress Image Free Online (JPEG, PNG, WebP) | C Wow",
    seoDescription:
      "Compress JPEG, PNG, and WebP images with adjustable quality. See the real size change, free and browser-based.",
  },
  {
    id: "image-convert",
    slug: "image-convert",
    name: "Convert Image Format",
    category: "image",
    description: "Convert between JPG, PNG, and WebP with transparency and background options.",
    keywords: ["image", "convert", "jpg", "png", "webp", "format"],
    synonyms: ["convert image", "jpg to png", "png to jpg", "webp to jpg"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["image/jpeg", "image/png", "image/webp"],
    batch: true,
    mode: "local",
    status: "ready",
    related: ["image-resize", "image-compress", "image-to-pdf"],
    seoTitle: "Convert Image Format Free (JPG, PNG, WebP) | C Wow",
    seoDescription:
      "Convert images between JPG, PNG, and WebP. Handle transparency with a background color, free and browser-based.",
  },
  {
    id: "image-crop",
    slug: "image-crop",
    name: "Crop Image",
    category: "image",
    description: "Crop images to a custom area or preset aspect ratio.",
    keywords: ["image", "crop", "aspect", "ratio", "trim", "cut"],
    synonyms: ["crop photo", "trim image", "aspect ratio crop"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["image/jpeg", "image/png", "image/webp"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["image-resize", "image-convert", "image-rotate"],
    seoTitle: "Crop Image Free Online | C Wow",
    seoDescription: "Crop images to a custom area or preset aspect ratio. Free and browser-based.",
  },
  {
    id: "image-rotate",
    slug: "image-rotate",
    name: "Rotate & Flip Image",
    category: "image",
    description: "Rotate images by 90° or flip horizontally and vertically.",
    keywords: ["image", "rotate", "flip", "mirror", "turn", "orientation"],
    synonyms: ["rotate image", "flip photo", "mirror image"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["image/jpeg", "image/png", "image/webp"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["image-crop", "image-resize"],
    seoTitle: "Rotate & Flip Image Free Online | C Wow",
    seoDescription:
      "Rotate images 90° or flip horizontally and vertically. Free and browser-based.",
  },
  {
    id: "image-adjust",
    slug: "image-adjust",
    name: "Adjust Image",
    category: "image",
    description: "Tune brightness, contrast, saturation, and apply grayscale.",
    keywords: ["image", "brightness", "contrast", "saturation", "grayscale", "filter", "adjust"],
    synonyms: ["adjust image", "image filters", "edit brightness contrast"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["image/jpeg", "image/png", "image/webp"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["image-rotate", "image-crop"],
    seoTitle: "Adjust Image Brightness, Contrast, Saturation Free | C Wow",
    seoDescription:
      "Adjust brightness, contrast, saturation, and apply grayscale to images. Free and browser-based.",
  },
  {
    id: "image-round-corners",
    slug: "image-round-corners",
    name: "Round Corners & Circle Crop",
    category: "image",
    description: "Add rounded corners or crop images into a circle with transparent output.",
    keywords: ["image", "round", "corners", "circle", "circular", "crop", "avatar"],
    synonyms: ["round corners", "circle crop", "circular image", "make avatar"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["image/png"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["image-crop", "image-convert"],
    seoTitle: "Round Corners & Circle Crop Image Free | C Wow",
    seoDescription:
      "Add rounded corners or crop images into a circle with transparent PNG output. Free and browser-based.",
  },
  {
    id: "image-palette",
    slug: "extract-color-palette",
    name: "Extract Color Palette",
    category: "image",
    description: "Pull a dominant color palette from any image as hex codes.",
    keywords: ["image", "color", "palette", "extract", "hex", "swatches"],
    synonyms: ["color palette from image", "extract colors", "image colors"],
    inputKinds: ["image"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["palette-builder", "contrast-checker", "gradient-builder"],
    seoTitle: "Extract Color Palette from Image Free | C Wow",
    seoDescription:
      "Extract a dominant color palette from any image as hex codes. Free and browser-based.",
  },
];
