import type { ToolDefinition } from "./tool-types";

export const PDF_TOOLS: ToolDefinition[] = [
  {
    id: "pdf-merge",
    slug: "merge-pdf",
    name: "Merge PDF",
    category: "pdf",
    tags: ["combine", "join"],
    description: "Combine multiple PDF files into one document with custom page order.",
    keywords: ["pdf", "merge", "combine", "join", "concatenate"],
    synonyms: ["combine pdf files", "join pdfs", "put pdfs together"],
    inputKinds: ["file"],
    accepts: ["application/pdf"],
    outputs: ["application/pdf"],
    batch: true,
    mode: "local",
    status: "ready",
    limits: "Up to 50 MB total. PDF 1.7 and below.",
    related: ["pdf-split", "image-to-pdf", "pdf-rotate"],
    faqs: [
      {
        q: "Is my PDF uploaded anywhere?",
        a: "No. Merging happens entirely in your browser. Your files never leave your device.",
      },
      {
        q: "Can I reorder pages?",
        a: "Yes. Drag files to reorder them before merging. The final PDF follows that order.",
      },
      {
        q: "Are encrypted PDFs supported?",
        a: "Password-protected PDFs cannot be merged. Remove the password first.",
      },
    ],
    featured: true,
    seoTitle: "Merge PDF Online Free — Combine PDFs in Your Browser | C Wow",
    seoDescription:
      "Merge multiple PDF files into one document for free. Drag to reorder, combine instantly, and download — all in your browser, no upload required.",
  },
  {
    id: "pdf-split",
    slug: "split-pdf",
    name: "Split PDF",
    category: "pdf",
    tags: ["extract", "divide"],
    description: "Split a PDF by page ranges or extract selected pages into a new file.",
    keywords: ["pdf", "split", "extract", "pages", "divide", "range"],
    synonyms: ["split pdf", "extract pages from pdf", "divide pdf"],
    inputKinds: ["file"],
    accepts: ["application/pdf"],
    outputs: ["application/pdf"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "Up to 50 MB. PDF 1.7 and below.",
    related: ["pdf-merge", "pdf-rotate", "pdf-extract-text"],
    faqs: [
      {
        q: "How do I specify pages?",
        a: "Use ranges like 1-3, 5, 8-10. Each range becomes a separate output PDF.",
      },
      {
        q: "Can I extract a single page?",
        a: "Yes. Enter a single page number like 4 to extract just that page.",
      },
    ],
    seoTitle: "Split PDF by Pages or Ranges Free | C Wow",
    seoDescription:
      "Split a PDF into multiple files by page ranges or extract specific pages. Free, browser-based, no upload.",
  },
  {
    id: "pdf-rotate",
    slug: "rotate-pdf",
    name: "Rotate PDF Pages",
    category: "pdf",
    description: "Rotate all or selected pages of a PDF by 90, 180, or 270 degrees.",
    keywords: ["pdf", "rotate", "turn", "orientation", "degrees"],
    synonyms: ["rotate pdf", "turn pdf pages", "fix pdf orientation"],
    inputKinds: ["file"],
    accepts: ["application/pdf"],
    outputs: ["application/pdf"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["pdf-split", "pdf-merge"],
    seoTitle: "Rotate PDF Pages Free Online | C Wow",
    seoDescription:
      "Rotate PDF pages 90, 180, or 270 degrees. Free and browser-based — your file stays on your device.",
  },
  {
    id: "pdf-extract-text",
    slug: "extract-pdf-text",
    name: "Extract PDF Text",
    category: "pdf",
    description: "Pull embedded text out of a PDF and save it as a plain TXT file.",
    keywords: ["pdf", "text", "extract", "txt", "copy", "content"],
    synonyms: ["get text from pdf", "copy pdf text", "pdf to text"],
    inputKinds: ["file"],
    accepts: ["application/pdf"],
    outputs: ["text/plain"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "Extracts embedded text only. Scanned PDFs without a text layer need OCR.",
    related: ["pdf-split", "pdf-merge"],
    faqs: [
      {
        q: "Why is the extracted text empty?",
        a: "The PDF may be a scanned image without a text layer. This tool reads embedded text, not images. Use an OCR tool for scans.",
      },
    ],
    seoTitle: "Extract Text from PDF to TXT Free | C Wow",
    seoDescription:
      "Extract embedded text from a PDF and download it as a TXT file. Free, browser-based, no upload.",
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    name: "Images to PDF",
    category: "pdf",
    description: "Combine JPG, PNG, or WebP images into a single PDF document.",
    keywords: ["image", "pdf", "jpg", "png", "convert", "combine", "pictures"],
    synonyms: ["pictures into one document", "images to pdf", "jpg to pdf", "png to pdf"],
    inputKinds: ["file"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    outputs: ["application/pdf"],
    batch: true,
    mode: "local",
    status: "ready",
    related: ["pdf-merge", "image-resize", "image-convert"],
    featured: true,
    seoTitle: "Convert Images to PDF Free (JPG, PNG, WebP) | C Wow",
    seoDescription:
      "Combine JPG, PNG, and WebP images into one PDF. Drag to reorder, free and browser-based.",
  },
  {
    id: "pdf-to-images",
    slug: "pdf-to-images",
    name: "PDF to Images",
    category: "pdf",
    description: "Render each page of a PDF as a PNG image, individually or as a ZIP.",
    keywords: ["pdf", "image", "png", "render", "rasterize", "pages"],
    synonyms: ["pdf to png", "convert pdf to images", "pdf pages to pictures"],
    inputKinds: ["file"],
    accepts: ["application/pdf"],
    outputs: ["image/png"],
    batch: false,
    mode: "local",
    status: "ready",
    limits: "Up to 50 MB. Rendering happens in your browser.",
    related: ["pdf-split", "image-resize"],
    seoTitle: "Convert PDF to PNG Images Free | C Wow",
    seoDescription:
      "Render PDF pages as PNG images, individually or as a ZIP. Free and browser-based.",
  },
  {
    id: "text-to-pdf",
    slug: "text-to-pdf",
    name: "Text to PDF",
    category: "pdf",
    description: "Create a clean, paginated PDF from plain text with proper wrapping.",
    keywords: ["text", "pdf", "create", "generate", "document", "txt"],
    synonyms: ["text to pdf", "make pdf from text", "convert txt to pdf"],
    inputKinds: ["text"],
    outputs: ["application/pdf"],
    batch: false,
    mode: "local",
    status: "ready",
    related: ["image-to-pdf", "pdf-merge"],
    seoTitle: "Convert Text to PDF Free Online | C Wow",
    seoDescription:
      "Create a paginated PDF from plain text with proper line wrapping. Free and browser-based.",
  },
];
